# Generated by Django 5.2.18 on 2026-10-07 00:07

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('group', models.CharField(choices=[('cameras', 'Caméras'), ('recording', 'Enregistrement'), ('alarm', 'Alarme'), ('access', "Contrôle d'accès"), ('accessories', 'Accessoires')], default='cameras', max_length=20)),
                ('name_fr', models.CharField(max_length=80, verbose_name='Nom (FR)')),
                ('name_ar', models.CharField(blank=True, max_length=80, verbose_name='Nom (AR)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'catégorie',
                'ordering': ['order', 'name_fr'],
            },
            bases=(shop.models.Bilingual, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Produit'), ('pack', "Pack d'installation"), ('service', 'Service (alarme, accès...)')], default='product', max_length=10, verbose_name='Type')),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(blank=True, max_length=40, verbose_name='Marque')),
                ('name_fr', models.CharField(max_length=120, verbose_name='Nom (FR)')),
                ('name_ar', models.CharField(blank=True, max_length=120, verbose_name='Nom (AR)')),
                ('short_fr', models.CharField(blank=True, max_length=160, verbose_name='Accroche (FR)')),
                ('short_ar', models.CharField(blank=True, max_length=160, verbose_name='Accroche (AR)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('specs_fr', models.TextField(blank=True, help_text='Une par ligne.', verbose_name='Caractéristiques (FR)')),
                ('specs_ar', models.TextField(blank=True, help_text='Une par ligne.', verbose_name='Caractéristiques (AR)')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Vide = sur devis. 0 = gratuit.', max_digits=10, null=True, verbose_name='Prix (MAD)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Ancien prix (MAD)')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Photo')),
                ('art', models.CharField(choices=[('indoor', 'Caméra intérieure'), ('bullet', 'Caméra extérieure'), ('ptz', 'Caméra PTZ / dôme'), ('doorbell', 'Sonnette vidéo'), ('nvr', 'Enregistreur'), ('hdd', 'Disque dur'), ('alarm', "Centrale d'alarme"), ('sensor', 'Détecteur'), ('siren', 'Sirène'), ('keypad', 'Lecteur badge / clavier'), ('finger', 'Empreinte digitale'), ('intercom', 'Interphone vidéo'), ('lock', 'Serrure connectée'), ('cable', 'Câble / accessoire'), ('pack', 'Pack caméras'), ('service', 'Service / technicien')], default='bullet', max_length=10, verbose_name='Dessin par défaut')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant (accueil)')),
                ('active', models.BooleanField(default=True, verbose_name='Visible')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'produit / pack / service',
                'verbose_name_plural': 'produits, packs et services',
                'ordering': ['order', 'id'],
            },
            bases=(shop.models.Bilingual, models.Model),
        ),
    ]
